name: hub

on:
  repository_dispatch:
    types: [publish_tag]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  HOPPSCOTH_RELEASE: ${{ github.event.client_payload.tag_name }}
  HOPPSCOTH_MAJOR: ${{ github.event.client_payload.tag_major }}

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          build-args: |
            HOPPSCOTH_RELEASE=${{ env.HOPPSCOTH_RELEASE }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.HOPPSCOTH_RELEASE }}
            ${{ env.IMAGE_NAME }}:${{ env.HOPPSCOTH_MAJOR }}
            ${{ env.IMAGE_NAME }}:latest
