name: Publish Container Image

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [publish_tag]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            Akurosia/hoppscotch
            ghcr.io/Akurosia/hoppscotch
          tags: |
            type=raw,value=${{ github.event.client_payload.tag_name }}
            type=raw,value=${{ github.event.client_payload.tag_major }}
            type=raw,value=latest
          labels: |
            maintainer=Akurosia
            org.opencontainers.image.authors=linuxserver.io,github.com/hoppscotch/hoppscotch,github.com/Akurosia/hoppscotch-docker
            org.opencontainers.image.licenses=GPL-3.0-only,MIT
            org.opencontainers.image.title=Hoppscotch docker
            org.opencontainers.image.description=All-in-one hoppscotch image that works with one domain and have embed smtp
            org.opencontainers.image.version=${{ github.event.client_payload.tag_name }}
            org.opencontainers.image.documentation=https://github.com/Akurosia/hoppscotch-docker#application-setup
            org.opencontainers.image.vendor=Hoppscotch

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password:  ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          provenance: true
          sbom: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            HOPPSCOTH_RELEASE=${{ github.event.client_payload.tag_name }}
          tags: ${{ steps.meta.outputs.tags }}
          platforms: |
            linux/amd64
            linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
